export type ProgramCategory =
  | "all"
  | "200hs"
  | "100hs"
  | "intensive"
  | "retreats"
  | "daily";

export interface ProgramListing {
  id: string;
  title: string;
  category: Exclude<ProgramCategory, "all">;
  location: string;
  locationSlug: "goa" | "dharamshala" | "online";
  duration: string;
  priceUSD: number | null;
  priceLabel: string;
  href: string;
  image: string;
  dates: string[];
  allInclusive?: boolean;
}

export const PROGRAM_FILTERS: { id: ProgramCategory; label: string }[] = [
  { id: "all", label: "All" },
  { id: "200hs", label: "200hs Training" },
  { id: "100hs", label: "100hs Training" },
  { id: "intensive", label: "8-Day Intensive" },
  { id: "retreats", label: "Retreats" },
  { id: "daily", label: "Daily Classes" },
];

export const programsCatalog: ProgramListing[] = [
  {
    id: "200-goa-alignment",
    title: "200-Hour Alignment Yoga TTC in Goa, Arambol",
    category: "200hs",
    location: "Arambol, Goa",
    locationSlug: "goa",
    duration: "24 Days",
    priceUSD: null,
    priceLabel: "€1,200",
    href: "/goa/200-hour-yttc",
    image: "/gallery/program-200-goa-alignment.jpg",
    dates: [
      "4 Nov – 25 Nov 2026",
      "3 Dec – 24 Dec 2026",
      "6 Jan – 27 Jan 2027",
      "4 Feb – 25 Feb 2027",
      "2 Mar – 23 Mar 2027",
    ],
    allInclusive: true,
  },
  {
    id: "200-goa-multi",
    title: "200-Hour Multi-Style YTTC in Goa, Arambol",
    category: "200hs",
    location: "Arambol, Goa",
    locationSlug: "goa",
    duration: "24 Days",
    priceUSD: null,
    priceLabel: "€1,200",
    href: "/goa/200-hour-yttc",
    image: "/gallery/program-200-goa-multi.jpg",
    dates: [
      "21 Nov – 12 Dec 2026",
      "16 Dec – 6 Jan 2027",
      "21 Jan – 11 Feb 2027",
      "18 Feb – 11 Mar 2027",
      "9 Mar – 30 Mar 2027",
    ],
    allInclusive: true,
  },
  {
    id: "200-dharamshala",
    title: "200-Hour Multi-Style & Alignment YTTC in Dharamshala",
    category: "200hs",
    location: "Bhagsu Nag, Dharamshala",
    locationSlug: "dharamshala",
    duration: "24 Days",
    priceUSD: 950,
    priceLabel: "$950",
    href: "/dharamshala/200-hour-yttc",
    image: "/gallery/program-200-dharamshala.jpg",
    dates: [
      "25 Apr – 16 May 2026",
      "23 May – 13 Jun 2026",
      "18 Jun – 9 Jul 2026",
      "18 Jul – 8 Aug 2026",
      "19 Aug – 9 Sep 2026",
    ],
    allInclusive: true,
  },
  {
    id: "100-goa-alignment",
    title: "100-Hour Alignment Yoga TTC in Goa, Arambol",
    category: "100hs",
    location: "Arambol, Goa",
    locationSlug: "goa",
    duration: "11 Days",
    priceUSD: 550,
    priceLabel: "$550",
    href: "/goa/100-hour-ttc",
    image: "/gallery/program-100-goa-alignment.jpg",
    dates: [
      "4 Nov – 14 Nov 2026",
      "4 Dec – 14 Dec 2026",
      "6 Jan – 16 Jan 2027",
      "5 Feb – 15 Feb 2027",
      "2 Mar – 12 Mar 2027",
    ],
    allInclusive: true,
  },
  {
    id: "100-goa-multi",
    title: "100-Hour Multi-Style Yoga TTC in Goa, Arambol",
    category: "100hs",
    location: "Arambol, Goa",
    locationSlug: "goa",
    duration: "11 Days",
    priceUSD: 550,
    priceLabel: "$550",
    href: "/goa/100-hour-ttc",
    image: "/gallery/program-100-goa-multi.jpg",
    dates: [
      "21 Nov – 1 Dec 2026",
      "16 Dec – 26 Dec 2026",
      "21 Jan – 31 Jan 2027",
      "18 Feb – 1 Mar 2027",
      "9 Mar – 19 Mar 2027",
    ],
    allInclusive: true,
  },
  {
    id: "100-dharamshala",
    title: "100-Hour Yoga Teacher Training in Dharamshala",
    category: "100hs",
    location: "Bhagsu Nag, Dharamshala",
    locationSlug: "dharamshala",
    duration: "11 Days",
    priceUSD: 550,
    priceLabel: "$550",
    href: "/dharamshala/100-hour-ttc",
    image: "/gallery/program-100-dharamshala.jpg",
    dates: [
      "28 Apr – 8 May 2026",
      "9 May – 19 May 2026",
      "23 May – 2 Jun 2026",
      "5 Jun – 15 Jun 2026",
      "18 Jun – 29 Jun 2026",
      "3 Jul – 13 Jul 2026",
      "18 Jul – 28 Jul 2026",
      "4 Aug – 14 Aug 2026",
      "19 Aug – 29 Aug 2026",
      "2 Sep – 12 Sep 2026",
    ],
    allInclusive: true,
  },
  {
    id: "8day-goa",
    title: "8-Day Intensive Alignment Course in Goa",
    category: "intensive",
    location: "Arambol, Goa",
    locationSlug: "goa",
    duration: "8 Days",
    priceUSD: null,
    priceLabel: "€280",
    href: "/goa/8-day-intensive",
    image: "/gallery/program-8day-goa.jpg",
    dates: [
      "23 Dec – 30 Dec 2026",
      "5 Jan – 12 Jan 2027",
      "20 Jan – 27 Jan 2027",
      "4 Feb – 11 Feb 2027",
      "18 Feb – 25 Feb 2027",
    ],
    allInclusive: false,
  },
  {
    id: "8day-dharamshala",
    title: "8-Day Intensive Alignment Yoga Course in Dharamshala",
    category: "intensive",
    location: "Bhagsu Nag, Dharamshala",
    locationSlug: "dharamshala",
    duration: "8 Days",
    priceUSD: 150,
    priceLabel: "$150",
    href: "/dharamshala/8-day-intensive",
    image: "/gallery/program-8day-dharamshala.jpg",
    dates: [
      "28 Apr – 5 May 2026",
      "9 May – 16 May 2026",
      "5 Jun – 12 Jun 2026",
      "3 Jul – 10 Jul 2026",
      "4 Aug – 11 Aug 2026",
      "2 Sep – 9 Sep 2026",
    ],
    allInclusive: false,
  },
  {
    id: "retreat-6",
    title: "6-Day Yoga Retreat",
    category: "retreats",
    location: "Goa",
    locationSlug: "goa",
    duration: "6 Days",
    priceUSD: null,
    priceLabel: "Enquiry",
    href: "/retreats#6-day",
    image: "/gallery/program-retreat-6.jpg",
    dates: ["See retreats page"],
  },
  {
    id: "retreat-10",
    title: "10-Day Yoga Retreat",
    category: "retreats",
    location: "Goa",
    locationSlug: "goa",
    duration: "10 Days",
    priceUSD: null,
    priceLabel: "Enquiry",
    href: "/retreats#10-day",
    image: "/gallery/program-retreat-10.jpg",
    dates: ["See retreats page"],
  },
  {
    id: "daily-goa",
    title: "Daily Drop-In Classes in Goa",
    category: "daily",
    location: "Arambol, Goa",
    locationSlug: "goa",
    duration: "90 Mins",
    priceUSD: null,
    priceLabel: "₹600",
    href: "/goa/daily-classes",
    image: "/gallery/program-daily-goa.jpg",
    dates: ["Open daily"],
  },
  {
    id: "daily-dharamshala",
    title: "Daily Drop-In Classes in Dharamshala",
    category: "daily",
    location: "Bhagsu Nag, Dharamshala",
    locationSlug: "dharamshala",
    duration: "90 Mins",
    priceUSD: null,
    priceLabel: "₹600",
    href: "/dharamshala/daily-classes",
    image: "/gallery/program-daily-dharamshala.jpg",
    dates: ["Open daily"],
  },
];
